### ISSUE TITLE
Move the base image from Debian Unstable to Xenial

### ISSUE THREAD

**Issue by tanty** [Igalia/mesa-dockerfiles#4]
This will enable easier integration with different LLVM versions and, also, will be closer to what we have in mesa's upstream travis integration.

**Comment by jasuarez** [comment]
Changing the issue to use Xenial instead of Trusty.

Ubuntu Xenial (16.04) is the latest LTS version. The only reason to use Trusty is because it has LLVM 3.3 already packaged. But other than that, it isn't worth: it doesn't contain newer LLVM versions, it has dependencies older than the ones in Xenial, and it will be deprecated soon.

For this reason let's stick to Ubuntu Xenial.

This release does not have LLVM 3.3 as package. So meanwhile we will compile this version in the proper Docker file.

**Comment by jasuarez** [comment]
Fixed in commit 1cbf7ed
